-- Auto-generated seed data mirroring current DEFAULT_PROGRAMS / DEFAULT_ROTATIVE_RATES
-- from src/lib/db.ts, plus operational defaults (WhatsApp numbers, stream URLs) and
-- the bootstrap owner account. Applied once via `wrangler d1 execute`.

INSERT INTO users (id, email, role, status, created_at)
  VALUES (lower(hex(randomblob(16))), 'somoslucitech@gmail.com', 'owner', 'active', (unixepoch()*1000));

INSERT INTO settings (key, value, updated_at) VALUES
  ('whatsapp_song_request', '"584144001071"', (unixepoch()*1000)),
  ('whatsapp_advertising', '"584244001367"', (unixepoch()*1000)),
  ('stream_url', '"https://radio.bonchonaradio.com:8443/stream"', (unixepoch()*1000)),
  ('stream_metadata_url', '"https://radio.bonchonaradio.com:8443/status-json.xsl"', (unixepoch()*1000)),
  ('rotative_rates', '[{"freq":"6 veces al día","durations":[{"time":"20s","price":200},{"time":"30s","price":270},{"time":"40s","price":330},{"time":"1m","price":380}]},{"freq":"8 veces al día","durations":[{"time":"20s","price":270},{"time":"30s","price":360},{"time":"40s","price":440},{"time":"1m","price":510}]},{"freq":"10 veces al día","durations":[{"time":"20s","price":340},{"time":"30s","price":450},{"time":"40s","price":550},{"time":"1m","price":640}]}]', (unixepoch()*1000));

INSERT INTO programs (id, sort_order, time, title, locutor, banner, description, rich_text, price) VALUES
  ('que-paso-ayer', 0, '08:00 AM - 10:00 AM', '¿Qué pasó ayer?', 'Alejandra Melian y Alejandro Rodríguez', '/programas/que_paso_ayer.png', '¿Qué pasó ayer? es tu magazine matutino definitivo, liderado por el carisma de Alejandra Melian y Alejandro Rodríguez. Despierta con el pulso vibrante de la farándula, las noticias de actualidad más impactantes y un análisis entretenido de lo que realmente importa. El programa ideal para empezar el día con energía, bien informado y con la dosis perfecta de picardía que solo Bonchona te ofrece.', 'Tu mañana ya no será igual. Sintoniza un espacio donde la actualidad se encuentra con el entretenimiento puro. Noticias, tendencias y la mejor compañía para que no te pierdas de nada.', 350),
  ('concursos-y-variedades', 1, '10:00 AM - 12:00 PM', 'Mucha People', 'Eduardo Rod y Víctor Matite', '/programas/mucha_pipol.png', 'La alegría se apodera de tus mañanas en Mucha People, el corazón de Concursos y Variedades. Eduardo Rod y Víctor Matite transforman tu radio en una fiesta interactiva llena de juegos dinámicos, entrevistas exclusivas con tus artistas favoritos y sorpresas que te mantendrán pegado al dial. Es el espacio donde el protagonista eres tú, con la mejor energía de Valencia de lunes a viernes.', 'De 10 a 12, vive la experiencia Mucha People. Risas, premios y la conexión total con la gente que hace del centro del país un lugar bonchón.', 200),
  ('te-lo-dije', 2, '01:00 PM - 03:00 PM', '¡Te lo dije!', 'Paola Meza y Richhel Aponte', '/programas/te_lo_dije.png', '¡Te lo dije! es el punto de encuentro donde Paola Meza y Richhel Aponte te ponen al día con todo lo que necesitas saber. Desde los datos curiosos más asombrosos hasta la información deportiva más relevante a nivel regional, nacional e internacional. Un espacio ágil, inteligente y con mucha personalidad que marca la pauta informativa de tus tardes, de lunes a viernes por Bonchona 107.1 FM.', 'Entérate de todo antes que nadie. Deportes, curiosidades y el análisis fresco que estabas buscando para tus mediodías.', 200),
  ('favoritas-107', 3, '04:00 PM - 06:00 PM', 'Favoritas 107', 'Carlos Briceño Jr.', '/programas/favoritas.png', 'Favoritas 107 es el resumen musical de mayor impacto en el país, conducido por Carlos Briceño Jr. Sumérgete en un viaje por los éxitos más recientes y lo más sonado en el panorama musical global. Con una selección curada para los oídos más exigentes, este espacio es el refugio perfecto para los amantes del buen ritmo. Disfruta de 4 a 6 de la tarde de la mejor selección musical en un solo lugar, con el sello de calidad Briceño.', 'El conteo más esperado del día. Los hits que dominan las listas mundiales suenan primero y mejor en tus Favoritas 107.', 350);
